require 'open-uri'
require 'nokogiri'
require 'pry'
require 'launchy'
require_relative '../lib/random_movie_picker/categories'
require_relative '../lib/random_movie_picker/cli'
require_relative '../lib/random_movie_picker/movie'
require_relative '../lib/random_movie_picker/version'